version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/e2e/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/web/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/api/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/api/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
