sudo: required
services: 
- docker
language: bash
script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker-compose build
#  - > 
#   if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then 
  - echo "$DOCKER_PASS" | docker login -u="$DOCKER_USER" --password-stdin
  - docker push stefanschoof/espresso
#   fi 
