variables:
  TERRAFORM_VERSION: 0.12.6

schedules:
- cron: "0 0 * * THU"
  displayName: Weekly build
  branches:
    include:
    - master
  always: true

stages:
- stage: build
  jobs:
  - template: node/build.yml
  - template: func/build.yml
  - template: web/build.yml
  - template: deploy/build.yml
  - template: e2etest/build.yml

- stage: test
  condition: and(succeeded('build'), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/greenkeeper/')))
  jobs:
  - template: deploy.yml
    parameters:
      environment: test
      sshEndpoint: dockerhost
      containerPoolVmImage: ubuntu-18.04
      test: true

- stage: prod
  condition: and(succeeded('test'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: deploy.yml
    parameters:
      environment: prod
      sshEndpoint: 'pi devops'
      test: false
      containerPoolName: Home
      dockerTag: latest
      testingCmd: ''
