stages:

- stage: test
  jobs:
  - deployment: deploy
    environment: test
    pool: Hosted Ubuntu 1604
    variables:
      KEYVAULTNAME: 'espresso-global'
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: |
              echo "##vso[task.setvariable variable=DeviceConnectionString;issecret=true;isOutput=true]***"
              echo "##vso[task.setvariable variable=NodeInstrumentationKey;issecret=true;isOutput=true]***"
              echo "##vso[task.setvariable variable=WebsiteUrl;isOutput=true]https://espressopitest.z6.web.core.windows.net/"
            name: iac
  - deployment: container
    environment: test
    dependsOn: deploy
    pool: Hosted Ubuntu 1604
    variables:
      NodeInstrumentationKey: $[ dependencies.deploy.outputs['iac.NodeInstrumentationKey'] ]
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: printenv | sort
