phases:
- phase: Phase_1
  displayName: Node
  queue:
    name: Hosted Ubuntu 1604

  steps:
  - task: Docker@1
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: 'docker hub sschoof'
      command: login

  - bash: ./dockerbuild.sh
    workingDirectory: node
    displayName: 'docker build'
    env:
     - PUSH: true
     - USECACHEFROM: true

  - task: CopyFiles@2
    displayName: 'Copy Files to staging'
    inputs:
      SourceFolder: 'node'
      Contents: |
        docker-compose.yml
        pideploy.sh
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: node

- phase: Phase_2
  displayName: function
  queue:
    name: Hosted Ubuntu 1604

  steps:
  - bash: |
     npm install
     npm test
     npm run build
     npm run lint
    workingDirectory: func
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: func'
    inputs:
      PathtoPublish: func/dist
      ArtifactName: func

- phase: Phase_3
  displayName: web
  queue:
    name: Hosted Ubuntu 1604

  steps:
  - bash: |
     npm install
     npm test
     npm run build
     npm run lint
    workingDirectory: web
    displayName: 'Build'
    env:
      FUNCTIONS_CODE: $(functions.code)

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: web'
    inputs:
      PathtoPublish: web/dist
      ArtifactName: web
