phases:
- phase: Phase_1
  displayName: Node
  queue:
    name: Hosted Ubuntu 1604

  steps:
  - bash: ./dockerbuild.sh
    workingDirectory: node
    displayName: 'docker build'

  - task: Docker@0
    displayName: 'Push image build'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: 'docker hub sschoof'
      action: 'Push an image'
      imageName: 'stefanschoof/espresso:build$(Build.BuildId)'

  - task: Docker@0
    displayName: 'Push image branch'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: 'docker hub sschoof'
      action: 'Push an image'
      imageName: 'stefanschoof/espresso:$(branchname)'

  - task: Docker@0
    displayName: 'Push image cache node'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: 'docker hub sschoof'
      action: 'Push an image'
      imageName: 'stefanschoof/espresso:build-cache-node'

  - task: Docker@0
    displayName: 'Push image cache cppbuilder'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: 'docker hub sschoof'
      action: 'Push an image'
      imageName: 'stefanschoof/espresso:build-cache-cppbuilder'

  - task: Docker@0
    displayName: 'Push image cache builder'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: 'docker hub sschoof'
      action: 'Push an image'
      imageName: 'stefanschoof/espresso:build-cache-builder'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: 'node/docker-compose.yml'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: node

- phase: Phase_2
  displayName: function
  queue:
    name: Hosted Ubuntu 1604

  steps:
  - bash: |
     npm install
     npm test
     npm run build
     npm run lint
    workingDirectory: func
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: func'
    inputs:
      PathtoPublish: func/dist
      ArtifactName: func

- phase: Phase_3
  displayName: web
  queue:
    name: Hosted Ubuntu 1604

  steps:
  - bash: |
     npm install
     npm test
     npm run build
     npm run lint
    workingDirectory: web
    displayName: 'Build'
    env:
      FUNCTIONS_CODE: $(functions.code)

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: web'
    inputs:
      PathtoPublish: web/dist
      ArtifactName: web
