variables:
  TERRAFORM_VERSION: 0.12.6

stages:
- stage: build
  jobs:
  - template: node/build.yml
  - template: func/build.yml
  - template: web/build.yml
  - template: deploy/build.yml
  - template: e2etest/build.yml

- stage: test
  condition: and(succeeded('build'), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/greenkeeper/')))
  jobs:
  - template: deploy.yml
    parameters:
      environment: test
      sshEndpoint: dockerhost
      test: true

- stage: prod
  condition: and(succeeded('test'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: deploy.yml
    parameters:
      environment: prod
      sshEndpoint: 'pi devops'
      test: false
      containerPool: Home
      dockerTag: latest
      testingCmd: ''
