parameters:
  environment: test
  sshEndpoint: dockerhost
  test: false
  containerPool: Hosted Ubuntu 1604
  dockerTag: dev
  testingCmd: echo

jobs:
- deployment: deploy
  environment: ${{ parameters.environment }}
  pool: Hosted Ubuntu 1604
  variables:
    KEYVAULTNAME: 'espresso-global'
    RELEASE_ENVIRONMENTNAME: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: Docker@1
          displayName: pull
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'docker hub sschoof'
            command: pull
            arguments: 'stefanschoof/espresso:build$(Build.BuildId)'
        - bash: 'docker tag stefanschoof/espresso:build$(Build.BuildId) stefanschoof/espresso:${{ parameters.dockerTag }}'
          displayName: 'Tag image'
        - task: Docker@1
          displayName: 'Push an image'
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'docker hub sschoof'
            command: 'Push an image'
            imageName: 'stefanschoof/espresso:${{ parameters.dockerTag }}'
        - bash: ./installteraform.sh
          displayName: 'Install terraform'
          workingDirectory: ../deploy
        - task: AzureCLI@1
          displayName: 'Infrastructure as Code'
          inputs:
            azureSubscription: 'Visual Studio Premium mit MSDN'
            scriptPath: '../deploy/iac.sh'
            workingDirectory: '../deploy'
            addSpnToEnvironment: true
        - task: AzureCLI@1
          displayName: deploy
          inputs:
            azureSubscription: 'Visual Studio Premium mit MSDN'
            scriptPath: '../deploy/deploy.sh'
            workingDirectory: '../deploy'
- deployment: container
  environment: ${{ parameters.environment }}
  dependsOn: deploy
  pool: ${{ parameters.containerPool }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureKeyVault@1
          displayName: 'Azure Key Vault: espresso-global'
          inputs:
            azureSubscription: 'Visual Studio Premium mit MSDN'
            KeyVaultName: 'espresso-global'
        - task: CopyFilesOverSSH@0
          displayName: 'Securely copy files to the remote machine'
          inputs:
            sshEndpoint: ${{ parameters.sshEndpoint }}
            sourceFolder: '../node'
            contents: 'docker-compose.yml'
            targetFolder: espresso
        - task: SSH@0
          displayName: 'Update docker'
          inputs:
            sshEndpoint: ${{ parameters.sshEndpoint }}
            runOptions: script
            scriptPath: '../node/pideploy.sh'
            args: '"$(DeviceConnectionString)" "$(NodeInstrumentationKey)" "$(Build.BuildId)" "${{ parameters.testingCmd }}"'
- ${{ if eq(parameters.test, 'true') }}:
  - deployment: e2etest
    environment: ${{ parameters.environment }}
    pool: Hosted VS2017
    dependsOn: container
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: e2etest
              downloadPath: .
          - task: AzureKeyVault@1
            displayName: 'Azure Key Vault: espresso-global'
            inputs:
              azureSubscription: 'Visual Studio Premium mit MSDN'
              KeyVaultName: 'espresso-global'
          - powershell: '$env:testurl = $(Website URL)'
            displayName: 'Set Testurl'
          - task: Npm@1
            displayName: 'npm ci --production'
            inputs:
              command: custom
              customCommand: 'ci --production'
          - task: Npm@1
            displayName: e2etest
            inputs:
              command: custom
              customCommand: start
          - task: PublishTestResults@2
            displayName: 'Publish Test Results **/junit.xml'
            inputs:
              testResultsFiles: 'junit.xml'
            condition: succeededOrFailed()
  - deployment: destroy
    environment: ${{ parameters.environment }}
    dependsOn: e2etest
    pool: Hosted Ubuntu 1604
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadSecureFile@1
            displayName: 'Download secure file'
            inputs:
              secureFile: 'df843c96-fc0e-409f-b3fd-f5a318bee16b'
          - task: DownloadSecureFile@1
            displayName: 'Download secure file'
            inputs:
              secureFile: 'c93bf295-33c5-4902-bab1-0f0e9f2b5b11'
          - task: Bash@3
            displayName: 'destroy'
            inputs:
              targetType: filePath
              filePath: '../deploy/destroy.sh'
              workingDirectory: '../deploy'
