parameters:
  environment: test
  sshEndpoint: dockerhost
  test: false
  containerPool: Hosted Ubuntu 1604
  dockerTag: dev
  testingCmd: echo

jobs:
- job: deploy
  pool: Hosted Ubuntu 1604
  steps:
  - checkout: none
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: deploy
      path: deploy
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: web
      path: web
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: func
      path: func
  - task: Docker@1
    displayName: pull
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'docker hub sschoof'
      command: pull
      arguments: 'stefanschoof/espresso:build$(Build.BuildId)'
  - bash: 'docker tag stefanschoof/espresso:build$(Build.BuildId) stefanschoof/espresso:${{ parameters.dockerTag }}'
    displayName: 'Tag image'
  - task: Docker@1
    displayName: 'Push an image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'docker hub sschoof'
      command: 'Push an image'
      imageName: 'stefanschoof/espresso:${{ parameters.dockerTag }}'
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: $(TERRAFORM_VERSION)
  - task: TerraformTaskV1@0
    displayName: 'Terraform init'
    inputs:
      workingDirectory: deploy
      backendServiceArm: 'Visual Studio Premium mit MSDN'
      backendAzureRmResourceGroupName: espresso-tfstate
      backendAzureRmStorageAccountName: espressotfstate
      backendAzureRmContainerName: tfstate
      backendAzureRmKey: terraform.tfstate
  - task: TerraformTaskV1@0
    displayName: 'Terraform apply'
    inputs:
      command: apply
      commandOptions: -var-file="${{ parameters.environment }}.tfvars"
      workingDirectory: deploy
      environmentServiceNameAzureRM: 'Visual Studio Premium mit MSDN'
    env:
      TF_WORKSPACE: ${{ parameters.environment }}
  - task: PowerShell@2
    displayName: 'terraform output to devops'
    name: terraformOutput
    inputs:
      filePath: 'deploy/output.ps1'
      workingDirectory: 'deploy'
  - task: AzureCLI@1
    displayName: 'Deploy'
    inputs:
      azureSubscription: 'Visual Studio Premium mit MSDN'
      scriptPath: 'deploy/deploy.sh'
      workingDirectory: 'deploy'
    env:
      AZURERM_APPLICATION_INSIGHTS_WEB: $(terraformOutput.azurerm_application_insights_web)
      FUNCTION_APP: $(terraformOutput.function_app)
      FUNCTION_APP_HOSTNAME: $(terraformOutput.function_app_hostname)
      STORAGE_ACCOUNT: $(terraformOutput.storage_account)
- job: container
  dependsOn: deploy
  pool: ${{ parameters.containerPool }}
  variables:
    DeviceConnectionString: $[ dependencies.deploy.outputs['terraformOutput.iot_device_connection_string'] ]
    NodeInstrumentationKey: $[ dependencies.deploy.outputs['terraformOutput.azurerm_application_insights_node'] ]
  steps:
  - checkout: none
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: node
      path: .
  - task: CopyFilesOverSSH@0
    displayName: 'Securely copy files to the remote machine'
    inputs:
      sshEndpoint: ${{ parameters.sshEndpoint }}
      contents: 'docker-compose.yml'
      targetFolder: espresso
  - task: SSH@0
    displayName: 'Update docker'
    inputs:
      sshEndpoint: ${{ parameters.sshEndpoint }}
      runOptions: script
      scriptPath: 'pideploy.sh'
      args: '"$(DeviceConnectionString)" "$(NodeInstrumentationKey)" "$(Build.BuildId)" "${{ parameters.testingCmd }}"'
- ${{ if eq(parameters.test, 'true') }}:
  - job: e2etest
    pool: Hosted VS2017
    dependsOn: container
    steps:
    - checkout: none
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: e2etest
        path: .
    - task: Npm@1
      displayName: 'npm ci --production'
      inputs:
        command: custom
        customCommand: 'ci --production'
    - task: Npm@1
      displayName: e2etest
      inputs:
        command: custom
        customCommand: start
    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/junit.xml'
      inputs:
        testResultsFiles: 'junit.xml'
      condition: succeededOrFailed()
  - job: destroy
    dependsOn: e2etest
    pool: Hosted Ubuntu 1604
    steps:
    - checkout: none
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: $(TERRAFORM_VERSION)
    - task: TerraformTaskV1@0
      displayName: 'Terraform init'
      inputs:
        backendServiceArm: 'Visual Studio Premium mit MSDN'
        backendAzureRmResourceGroupName: espresso-tfstate
        backendAzureRmStorageAccountName: espressotfstate
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: terraform.tfstate
    - task: TerraformTaskV1@0
      displayName: 'Terraform destroy'
      inputs:
        command: destroy
        commandOptions: -var-file="test.tfvars" -target azurerm_virtual_machine.dockerhost -target azurerm_iothub.iothub
        environmentServiceNameAzureRM: 'Visual Studio Premium mit MSDN'
      env:
        TF_WORKSPACE: test
