jobs:
- job: function
  displayName: function
  pool: Hosted Ubuntu 1604

  steps:
  - bash: |
      set -e
      npm ci
      npm run build
      npm run test:ci
      npm run lint
    workingDirectory: func
    displayName: 'Build'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: func/junit.xml

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: func/coverage/cobertura-coverage.xml

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: func
      targetPath: func/dist

