jobs:
- job: deploy
  pool:
    vmImage: ubuntu-18.04

  steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: $(TERRAFORM_VERSION)
  - template: terraform.yml
    parameters:
      environment: test
  - template: terraform.yml
    parameters:
      environment: prod
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: deploy
      targetPath: deploy
