jobs:
- job: deploy
  condition: not(startsWith(variables['Build.SourceBranch'], 'refs/heads/greenkeeper/'))
  pool: Hosted Ubuntu 1604

  steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: $(TERRAFORM_VERSION)
  - template: terraform.yml
    parameters:
      environment: test
  - template: terraform.yml
    parameters:
      environment: prod
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: deploy
      targetPath: deploy
