INSTRUMENTATION_KEY=$1
FUNCTIONS_CODE=$2
FUNCTIONS_HOSTNAME=$3

sed -i \
    -e "s/<%INSTRUMENTATION_KEY%>/${INSTRUMENTATION_KEY}/" \
    -e "s/<%FUNCTIONS_CODE%>/${FUNCTIONS_CODE}/" \
    -e "s/<%FUNCTIONS_HOSTNAME%>/${FUNCTIONS_HOSTNAME}/" \
    ../web/dist/index.html
