parameters:
  environment: test

steps:
- task: TerraformTaskV1@0
  displayName: 'Terraform init ${{ parameters.environment }}'
  inputs:
    workingDirectory: deploy
    backendServiceArm: 'Visual Studio Premium mit MSDN'
    backendAzureRmResourceGroupName: espresso-tfstate
    backendAzureRmStorageAccountName: espressotfstate${{ parameters.environment }}
    backendAzureRmContainerName: tfstate
    backendAzureRmKey: terraform.tfstate
    commandOptions: '-reconfigure'
- task: TerraformTaskV1@0
  displayName: 'Terraform plan ${{ parameters.environment }}'
  inputs:
    command: plan
    commandOptions: '-var-file="${{ parameters.environment }}.tfvars" -lock-timeout=30m'
    workingDirectory: deploy
    environmentServiceNameAzureRM: 'Visual Studio Premium mit MSDN'
