jobs:
- job: node
  pool: Hosted Ubuntu 1604

  steps:
  - task: Docker@1
    displayName: 'docker login'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'docker hub sschoof'
      command: login

  - bash: ./enablecrosscompile.sh
    workingDirectory: node
    displayName: 'enable cross compile'

  - bash: ./startbuildkitd.sh
    workingDirectory: node
    displayName: 'start buildkitd'

  - bash: ./dockerbuild.sh
    workingDirectory: node
    displayName: 'docker build'
    env:
      BUILDKIT_HOST: tcp://0.0.0.0:1234

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: node/junit.xml

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: node/coverage/cobertura-coverage.xml

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: node
      targetPath: node

