[package]
name = "steckdose"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio-cdev = "0.4"
funksteckdose = "0.1.0"
rocket = "0.5.0-rc.1"