jobs:
- job: e2etest
  pool:
    vmImage: ubuntu-18.04

  steps:
  - bash: |
      set -e
      npm ci
      npm run build
      npm run lint
    workingDirectory: e2etest
    displayName: 'Build'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: e2etest
      targetPath: e2etest

