[package]
name = "steckdose"
version = "0.1.0"
edition = "2021"

[dependencies]
gpio-cdev = "0.5"
funksteckdose = { git = "https://github.com/StefanSchoof/funksteckdose", branch = "main" }
rocket = { version = "0.5.0-rc.3", default-features = false }
