name: build

on:
  push:
    branches:
      - "main"
      - "feature/*"
  workflow_dispatch:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta api
        id: meta-api
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/stefanschoof/espressoapi
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          bake-target: docker-metadata-action-api
      - name: Docker meta web
        id: meta-web
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/stefanschoof/espressoweb
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          bake-target: docker-metadata-action-web
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert bake json to hcl
        # workaround for https://github.com/docker/buildx/issues/756
        run: |
          wget https://github.com/kvz/json2hcl/releases/download/v0.0.6/json2hcl_v0.0.6_linux_amd64
          chmod +x json2hcl_v0.0.6_linux_amd64
          ./json2hcl_v0.0.6_linux_amd64 < ${{ steps.meta-web.outputs.bake-file }} | sed -E 's/"(target|tags|labels|args)"/\1/' > web.hcl
      - name: Build
        uses: docker/bake-action@v1.6.0
        with:
          files: |
            ./docker-bake.hcl
            ./web.hcl
            ${{ steps.meta-api.outputs.bake-file }}
          push: ${{ github.event_name != 'pull_request' }}
          set: "*.cache-to=type=gha,mode=max"
